file_name_storage = "blob.txt"
project           = "cmtr"
env_name          = "j5tku7ra"
module_name       = "mod7"
group             = "fd"
location          = "West US"
fw_sku_name       = "Standard_AzureFrontDoor"
fw_route_name     = "default"